version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: openshop-postgres
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "max_replication_slots=4"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openshop

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    platform: linux/amd64
    container_name: openshop-dbt
    restart: "no"
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "dbt",
          "debug",
          "--profiles-dir",
          "/root/.dbt",
          "--project-dir",
          "/usr/app/dbt"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - openshop

  redis:
    image: redis:7
    container_name: openshop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openshop

  mariadb:
    image: mariadb:10.6
    container_name: openshop-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD}
    volumes:
      - matomo_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - openshop

  matomo:
    image: matomo:latest
    container_name: openshop-matomo
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8001:80"
    volumes:
      - matomo_data:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: mariadb
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DB_PASSWORD}
      MATOMO_DATABASE_DBNAME: matomo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - openshop

  airflow:
    image: apache/airflow:2.9.1
    container_name: openshop-airflow
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${DATABASE_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRBYTE_API_URL: ${AIRBYTE_API_URL}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8082:8080"
    command: ["airflow", "standalone"]
    healthcheck:
      test: ["CMD", "airflow", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - openshop

  superset:
    image: apache/superset:2.1.0
    platform: linux/amd64
    container_name: openshop-superset
    restart: unless-stopped
    env_file: [ ./.env ]
    environment:
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - "8088:8088"
    volumes:
      - superset-home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py:ro
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "superset", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - openshop

networks:
  openshop:
    driver: bridge

volumes:
  pgdata:
  superset-home:
  matomo_data:
  airflow_logs:
  matomo_db:
