services:

  airflow-postgres:
    image: postgres:16
    container_name: airflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: analytics
    ports:
      - "5433:5432" 
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openshop

  airflow-redis:
    image: redis:7
    container_name: airflow-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openshop

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    restart: "no"
    env_file:
      - ./.env
    entrypoint: >
      /bin/bash -euxo pipefail -c "
        until pg_isready -h airflow-postgres -U analytics; do sleep 5; done &&
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true &&
        airflow sync-perm
      "
    depends_on:
      - airflow-postgres
      - airflow-redis
    networks:
      - openshop

  airflow-webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8082:8080"
    volumes:
      - ./01_ingest:/opt/pipeline/modules/01_ingest:ro
      - ./02_dbt:/opt/pipeline/modules/02_dbt:rw
      - ./02_dbtprofiles.yml:/home/airflow/.dbt/profiles.yml:ro
      - ./04_airflow/dags:/opt/airflow/dags:ro
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    networks:
      - openshop

  airflow-scheduler:
    build: 
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./01_ingest:/opt/pipeline/modules/01_ingest:ro
      - ./02_dbt:/opt/pipeline/modules/02_dbt:rw
      - ./02_dbtprofiles.yml:/home/airflow/.dbt/profiles.yml:ro
      - ./04_airflow/dags:/opt/airflow/dags:ro
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    networks:
      - openshop

networks:
  openshop:
    driver: bridge

volumes:
  airflow_pgdata:
  airflow_logs:
  airflow_plugins:
