name: "module2_dbt"
version: "1.0"
config-version: 2

profile: "default"

model-paths: ["models"]
seed-paths: []
snapshot-paths: []
test-paths: []
analysis-paths: []

models:
  module2_dbt:
    staging:
      +schema: raw
      +materialized: view
    core:
      +schema: analytics
      +materialized: table
