default:
  outputs:
    dev:
      type: postgres
      threads: 1
      # host: "{{ env_var('POSTGRES_HOST') }}"
      host: airflow-postgres
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'analytics') }}"
  target: dev
